name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    if: contains(github.event.head_commit.message, '[front]')
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install Dependencies
        run: npm ci
        working-directory: front_end
      
      - name: Run Lint
        run: npm run lint
        working-directory: front_end
      
      - name: Build
        run: npm run build
        working-directory: front_end
  
  # backend:
  #   if: contains(github.event.head_commit.message, '[back]')
  #   name: Backend Build and Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
      
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.22"
      
  #     - name: Install Dependencies
  #       run: go mod download
  #       working-directory: front_end
      
  #     - name: Build
  #       run: go build -o myapp .
  #       working-directory: back_end